### PR TITLE
Use dummy module to trigger semanticdb-scalac updates

### PR DESCRIPTION
**Pull request by lolgab**
Fixes: #71
### Extra improvements: 
- Use BuildInfo instead of custom code generation

### CODE REVIEW

**Comment by lolgab** [comment]
@joan38 @lefou This should make it :)

**Review by lefou — COMMENTED** [review]
Looks good to me.

**Comment by joan38** [comment]
Wait I don't understand why the previous code didn't work.
I have another project where we have them in lazy vals and it works. See https://github.com/joan38/kubernetes-client/pull/121/files

**Comment by lolgab** [comment]
I think it is because the lazy val value is [used in an `ivyDeps`](https://github.com/joan38/kubernetes-client/blob/master/build.sc#L35) while here it is.

**Comment by lolgab** [comment]
Now that you say it I could move it back to be a val and just add the dummy module which uses it. What do you think @joan38 ?

**Comment by lolgab** [comment]
Moved in a val in the last commit. It is much better! Cool that Scala Steward supports it.

**Comment by joan38** [comment]
Great thanks!

**Pull request merged**
