### PR TITLE
Bump scalafix to 0.11.0

### PR DESCRIPTION
**Pull request by carlosedp**
Ref. https://github.com/scalacenter/scalafix/releases/tag/v0.11.0

### CODE REVIEW

**Comment by bjaglin** [comment]
You might want to change https://github.com/joan38/mill-scalafix/blob/51277b3ffd7ed15f9fa85064e109ed330f3a81ad/README.md?plain=1#L39 since `OrganizeImports` is built-in! https://github.com/xuwei-k/scalafix-rules has a great set of rules if I could recommend another one.

**Comment by joan38** [comment]
Thanks guys!

**Comment by carlosedp** [comment]
Yay! Already refreshing Maven Central to check if the packages have been published :D

**Comment by joan38** [comment]
Done https://github.com/joan38/mill-scalafix/releases/tag/v0.3.0

**Pull request merged**
